#!/usr/bin/env bash

DSHIP_PWD=`pwd`
link=$(readlink "$0")
if [ "$link" !=  "" ]
then
  bin_dir=$( dirname "$link" )  
  #if softlink relate with relative path
  if [[ $bin_dir != /* ]]
  then
    cd `dirname "$0"`
    C_PWD=`pwd`
    bin_dir=${C_PWD}/${bin_dir}
    cd $DSHIP_PWD
  fi
else
  bin_dir=$( dirname "$0" )
fi

java -Xms256m -Xmx1024m -Duser.dir="$DSHIP_PWD" -Dfile.encoding=UTF-8 -classpath "${bin_dir}/lib/*" com.aliyun.odps.ship.DShip  "$@"
